# Generated by Django 4.2.6 on 2023-11-12 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('white_player', models.CharField(blank=True, null=True)),
                ('black_player', models.CharField(blank=True, null=True)),
                ('finished', models.BooleanField(blank=True, null=True)),
                ('result', models.BigIntegerField(blank=True, null=True)),
                ('white_player_chosen_square', models.CharField(blank=True, null=True)),
                ('black_player_chosen_square', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzles',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('starting_position', models.CharField(blank=True, null=True)),
                ('difficulty', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField()),
                ('email', models.CharField(blank=True, null=True)),
                ('year_of_birth', models.BigIntegerField(blank=True, null=True)),
                ('rating_elo', models.BigIntegerField(blank=True, null=True)),
                ('rating_puzzles', models.BigIntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolvedPuzzles',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.puzzles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleSolutions',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('move', models.CharField(blank=True, null=True)),
                ('puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.puzzles')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleProgress',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('current_move', models.BigIntegerField(blank=True, null=True)),
                ('puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.puzzles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='MoveHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('move', models.CharField(blank=True, null=True)),
                ('match', models.ForeignKey(blank=True, db_column='match_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.games')),
            ],
        ),
        migrations.CreateModel(
            name='GameParticipants',
            fields=[
                ('participant_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.games')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.users')),
            ],
        ),
    ]