# Generated by Django 4.2.6 on 2023-11-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='rating_elo',
            field=models.BigIntegerField(blank=True, default=1200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='rating_puzzles',
            field=models.BigIntegerField(blank=True, default=1200, null=True),
        ),
    ]
