# Generated by Django 4.2.3 on 2023-07-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gosha'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserNickname', models.CharField(max_length=20)),
                ('UserEmail', models.EmailField(max_length=100)),
                ('UserPassword', models.CharField(max_length=20)),
                ('UserRating', models.IntegerField(default=800)),
                ('UserStatus', models.CharField(choices=[('US', 'USER'), ('BN', 'BAN'), ('AD', 'ADMIN'), ('OW', 'OWNER')], default='US', max_length=2)),
                ('UserAvatar', models.CharField(default='TEST', max_length=100)),
                ('UserRegistrationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WhitePlayerHistoryRating', models.IntegerField()),
                ('BlackPlayerHistoryRating', models.IntegerField()),
                ('MatchCompletionTime', models.DateTimeField(auto_now_add=True)),
                ('PlayersUserID', models.ManyToManyField(to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatchIsRated', models.BooleanField(default=False)),
                ('PlayersUserID', models.ManyToManyField(to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Lobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LobbyIsRated', models.BooleanField(default=False)),
                ('LobbyTimeLimit', models.IntegerField(default=600)),
                ('LobbyCreatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
