# Generated by Django 4.2.3 on 2023-07-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_matchhistory_matches_lobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='PlayersUserID',
        ),
        migrations.AddField(
            model_name='matches',
            name='MatchResult',
            field=models.CharField(choices=[('B', 'BLACK WON'), ('W', 'WHITE WON'), ('D', 'DRAW'), ('A', 'ABORTED')], default='A'),
        ),
        migrations.CreateModel(
            name='MatchHistory_PlayersUserID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserColor', models.CharField(choices=[('B', 'BLACK'), ('W', 'WHITE')])),
                ('MatchHistoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.matchhistory')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
