# Generated by Django 4.2.6 on 2023-11-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_games_black_player_remove_games_white_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='chessboard_position',
            field=models.CharField(default='rnbqkbnrpppppppp11111111111111111111111111111111PPPPPPPPRNBQKBNR0000000000000000000000000000000000000000000000000000000000000000'),
        ),
        migrations.AlterField(
            model_name='games',
            name='black_player_chosen_square',
            field=models.CharField(default='-1'),
        ),
        migrations.AlterField(
            model_name='games',
            name='white_player_chosen_square',
            field=models.CharField(default='-1'),
        ),
    ]
