# Generated by Django 4.2.6 on 2023-11-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_matchhistory_playersuserid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameparticipants',
            fields=[
                ('participantid', models.BigIntegerField(db_column='ParticipantID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GameParticipants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('whiteplayer', models.TextField(blank=True, db_column='WhitePlayer', null=True)),
                ('blackplayer', models.TextField(blank=True, db_column='BlackPlayer', null=True)),
                ('finished', models.BooleanField(blank=True, db_column='Finished', null=True)),
                ('result', models.BigIntegerField(blank=True, db_column='Result', null=True)),
            ],
            options={
                'db_table': 'Games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movehistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('move', models.TextField(blank=True, db_column='Move', null=True)),
            ],
            options={
                'db_table': 'MoveHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puzzleprogress',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('currentmove', models.BigIntegerField(blank=True, db_column='CurrentMove', null=True)),
            ],
            options={
                'db_table': 'PuzzleProgress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puzzles',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('startingposition', models.TextField(blank=True, db_column='StartingPosition', null=True)),
                ('difficulty', models.BigIntegerField(blank=True, db_column='Difficulty', null=True)),
            ],
            options={
                'db_table': 'Puzzles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puzzlesolutions',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('move', models.TextField(blank=True, db_column='Move', null=True)),
            ],
            options={
                'db_table': 'PuzzleSolutions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solvedpuzzles',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SolvedPuzzles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='Password', null=True)),
                ('nickname', models.CharField(db_column='Nickname')),
                ('email', models.CharField(blank=True, db_column='Email', null=True)),
                ('yearofbirth', models.BigIntegerField(blank=True, db_column='YearOfBirth', null=True)),
                ('ratingelo', models.BigIntegerField(blank=True, db_column='RatingELO', null=True)),
                ('ratingpuzzles', models.BigIntegerField(blank=True, db_column='RatingPuzzles', null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.DeleteModel(
            name='Gosha',
        ),
        migrations.RemoveField(
            model_name='lobbies',
            name='LobbyCreatorID',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='PlayersUserID',
        ),
        migrations.RemoveField(
            model_name='matchhistory_playersuserid',
            name='MatchHistoryId',
        ),
        migrations.RemoveField(
            model_name='matchhistory_playersuserid',
            name='UserID',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Lobbies',
        ),
        migrations.DeleteModel(
            name='Matches',
        ),
        migrations.DeleteModel(
            name='MatchHistory',
        ),
        migrations.DeleteModel(
            name='MatchHistory_PlayersUserID',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
